---
- name: Deploy Flask Vision Board Application
  hosts: webservers
  become: true

  vars:
    docker_hub_user: "zehavab"
    image_name: "flask-vision-board"
    container_name: "flask_vision_app"

  tasks:
    - name: Remove existing container if it exists
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: true

    - name: Pull latest image from DockerHub
      docker_image:
        name: "{{ docker_hub_user }}/{{ image_name }}:latest"
        source: pull
        force_source: true

    - name: Run the new Flask container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_hub_user }}/{{ image_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
